import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
public class EX1 {
public static void main(String[] args) {
// Create and initialize a countries_list
...
// display the size of a the countries_list
...
// display the elements of the countries_list
...
// modify a list entry.
...
// sort countries_list in an ascending order.
...
// clear the list
...
}
private static void displayList(List<String> list) {
...
}
}
